# Generated by Django 6.0 on 2026-09-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="new_password",
        ),
    ]
